namespace: itd27m01
name: oracle
description: Ansible collection for Oracle RDBMS
version: 0.1.2
readme: README.md
authors:
  - ITD27M01 (https://github.com/itd27m01)
license_file: LICENSE
tags:
  - oracle
repository: https://github.com/ITD27M01/ansible-oracle-collection
homepage: https://github.com/ITD27M01/ansible-oracle-collection
issues: https://github.com/ITD27M01/ansible-oracle-collection
build_ignore:
  - '*.tar.gz'
  - '*.pyc'