namespace: itd27m01
name: ansible-oracle
description: Missing items for manage oracle_db
version: 0.1.0
readme: README.md
authors:
  - ITD27M01 (https://github.com/itd27m01)
license_file: LICENSE
tags:
  - ansible-oracle
repository: https://github.com/ITD27M01/ansible-oracle-collection
homepage: https://github.com/ITD27M01/ansible-oracle-collection
issues: https://github.com/ITD27M01/ansible-oracle-collection
build_ignore:
  - '*.tar.gz'
  - '*.pyc'